databaseChangeLog:
  - include:
      file: "db/changelog/2024/07/21-01-changelog.yaml"
  - include:
      file: "db/changelog/data/isbn/isbn-load.xml"
  - include:
      file: "db/changelog/data/biblio/biblio-load.xml"
